#include <iostream>
#include <fstream>
#include <sstream>
#include <vector>
#include <unordered_map>
#include <queue>
#include <random>
#include <algorithm>
#include <chrono>
#include <iomanip>
#include <limits>
using namespace std; using Clock=chrono::high_resolution_clock;
struct Edge{int to,w;}; using Graph=unordered_map<int,vector<Edge>>; struct Candidate{vector<int> path; int fitness;}; struct RunResult{long long edges; size_t nodes; double loadTime; double algoTime; int source,target,distance; vector<int> path;};
static double secs(Clock::time_point a,Clock::time_point b){return chrono::duration<double>(b-a).count();}
void addEdge(Graph&g,int u,int v){g[u].push_back({v,1}); g[v].push_back({u,1});}
Graph loadGraph(const string& file,long long maxEdges,long long& edgeCount,double& loadTime){auto st=Clock::now(); ifstream in(file); if(!in) throw runtime_error("Could not open dataset. Use unzipped as-skitter.txt."); Graph g; string line; edgeCount=0; while(getline(in,line)){ if(line.empty()||line[0]=='#') continue; stringstream ss(line); int u,v; if(ss>>u>>v){addEdge(g,u,v); edgeCount++;} if(maxEdges>0&&edgeCount>=maxEdges) break;} loadTime=secs(st,Clock::now()); return g;}
Candidate randomWalk(const Graph&g,int source,int target,int maxSteps,mt19937&rng){vector<int> path{source}; unordered_map<int,bool> seen; seen[source]=true; int cur=source; for(int i=0;i<maxSteps;i++){ if(cur==target) break; auto it=g.find(cur); if(it==g.end()||it->second.empty()) break; uniform_int_distribution<int> dist(0,(int)it->second.size()-1); int next=it->second[dist(rng)].to; if(seen[next] && next!=target) continue; path.push_back(next); seen[next]=true; cur=next;} int fit=(cur==target)?(int)path.size()-1:1000000000; return {path,fit};}
RunResult runHarmonySearch(const string& file,int source,long long maxEdges,int iterations,int harmonyMemorySize){long long edgeCount; double loadTime; Graph g=loadGraph(file,maxEdges,edgeCount,loadTime); if(!g.count(source)) throw runtime_error("Source node not found."); int target=0; for(auto&kv:g) target=max(target,kv.first); mt19937 rng(42); int maxSteps=50; vector<Candidate> memory; auto st=Clock::now(); for(int i=0;i<harmonyMemorySize;i++) memory.push_back(randomWalk(g,source,target,maxSteps,rng)); for(int it=0;it<iterations;it++){ Candidate c=randomWalk(g,source,target,maxSteps,rng); auto worst=max_element(memory.begin(),memory.end(),[](const Candidate&a,const Candidate&b){return a.fitness<b.fitness;}); if(c.fitness<worst->fitness) *worst=c; } auto best=min_element(memory.begin(),memory.end(),[](const Candidate&a,const Candidate&b){return a.fitness<b.fitness;}); double algo=secs(st,Clock::now()); int dist=(best==memory.end()?1000000000:best->fitness); vector<int> path=(best==memory.end()?vector<int>{}:best->path); return{edgeCount,g.size(),loadTime,algo,source,target,dist,path};}
void makeSvgBar(const string& filename,const string& title,const string& label,double value,const string& unit){ofstream out(filename); int bar=(int)(500*(value/max(1.0,value))); out<<"<svg xmlns='http://www.w3.org/2000/svg' width='800' height='300'><rect width='100%' height='100%' fill='white'/><text x='30' y='40' font-size='24' font-family='Arial'>"<<title<<"</text><text x='30' y='100' font-size='18' font-family='Arial'>"<<label<<"</text><rect x='200' y='75' width='"<<bar<<"' height='50' fill='steelblue'/><text x='"<<210+bar<<"' y='108' font-size='16' font-family='Arial'>"<<fixed<<setprecision(4)<<value<<" "<<unit<<"</text></svg>";}
void saveOutputs(const RunResult&r){ofstream csv("results.csv"); csv<<"algorithm,edges,nodes,load_time_seconds,algorithm_time_seconds,total_time_seconds,source,target,distance,path_length\n"; csv<<"Harmony Search,"<<r.edges<<","<<r.nodes<<","<<r.loadTime<<","<<r.algoTime<<","<<r.loadTime+r.algoTime<<","<<r.source<<","<<r.target<<","<<r.distance<<","<<r.path.size()<<"\n"; makeSvgBar("runtime_graph.svg","Harmony Search Runtime","Algorithm time",r.algoTime,"seconds"); makeSvgBar("path_length_graph.svg","Harmony Search Path Length","Path length",(double)r.path.size(),"nodes");}
int main(int argc,char*argv[]){try{string file="as-skitter.txt"; int source=0; long long maxEdges=100000; int iterations=5000; int hms=50; if(argc>=2) file=argv[1]; if(argc>=3) source=stoi(argv[2]); if(argc>=4) maxEdges=stoll(argv[3]); if(argc>=5) iterations=stoi(argv[4]); if(argc>=6) hms=stoi(argv[5]); cout<<"=============================================\nHarmony Search Algorithm Project\nStanford SNAP as-Skitter Dataset\n=============================================\n\n"; auto r=runHarmonySearch(file,source,maxEdges,iterations,hms); cout<<"Nodes Loaded        : "<<r.nodes<<"\nEdges Loaded        : "<<r.edges<<"\nGraph Load Time     : "<<fixed<<setprecision(4)<<r.loadTime<<" seconds\nHarmony Search Time : "<<r.algoTime<<" seconds\nTotal Runtime       : "<<r.loadTime+r.algoTime<<" seconds\nSource Node         : "<<r.source<<"\nTarget Node         : "<<r.target<<"\nBest Distance       : "; if(r.distance>=1000000000) cout<<"not found"; else cout<<r.distance<<" edge(s)"; cout<<"\nPath                : "; if(r.path.empty()||r.distance>=1000000000) cout<<"No complete path found. Increase iterations or use smaller graph."; else for(size_t i=0;i<r.path.size();i++) cout<<r.path[i]<<(i+1<r.path.size()?" -> ":""); cout<<"\n\nNote: Harmony Search is approximate and does not guarantee the shortest path.\nTime Complexity     : O(iterations * HMS * path_length) conceptually\nSpace Complexity    : O(V + E + HMS * path_length)\n"; saveOutputs(r); cout<<"\nCreated results.csv, runtime_graph.svg, and path_length_graph.svg\n";}catch(const exception&e){cerr<<"Error: "<<e.what()<<"\n";return 1;}}
